/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gjwzlsgpkmlawbscbtdz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdqd3psc2dwa21sYXdic2NidGR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5NjcxNDQsImV4cCI6MjA3NzU0MzE0NH0.hPbJxAnML4Ur-mEms68jlSFvjJ9QjJLk-tsf7IAFZag"